# Stubs for requests_mock.exceptions

from typing import Any

class MockException(Exception): ...

class NoMockAddress(MockException):
    request: Any = ...
    def __init__(self, request: Any) -> None: ...

class InvalidRequest(MockException): ...
