name: Lint

on:
  - push

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
        pip install -r typing-requirements.txt

    - name: Lint with flake8
      run: flake8 requests_mock tests

    - name: Lint type hinting with MyPy
      run: mypy requests_mock
